version: "3.9"

services:
  db:
    image: postgres
    container_name: recipes-db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

volumes:
  db-data:
