name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/recipe-app-test

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build server
        run: npm run build --if-present
      - name: Prettier
        run: npm run format:ci
      - name: ESLint
        run: npm run lint
      - name: TypeScript
        run: npm run check
      - name: Vitest
        env:
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          BCRYPT_ROUNDS: ${{ vars.BCRYPT_ROUNDS }}
          PORT: ${{ vars.PORT }}
        run: npm run test:ci
